### ISSUE TITLE
Videos don't load

### ISSUE THREAD

**Issue by tsuniox2** [Julzso23/smoothroll#68]
Similar websites also have the same issues , I think something changed on crunchyroll's end

**Comment by Julzso23** [comment]
Thanks for bringing this to my attention. Looks like Crunchyroll might've setup CORS, so we can't make requests from 3rd party domains anymore. Not much that can be done about this unfortunately.

**Comment by tsuniox2** [comment]
Umi.party (similar website like yours) has an extension that makes it work , is something like this possible

**Comment by Julzso23** [comment]
I'll look into it, thanks for the suggestion.

**Comment by Julzso23** [comment]
Ok, for now I've committed an extension folder that you can load unpacked in chrome to fix this issue. It's not the most elegant solution, but it should work. I've also added a message to the top of the site explaining how to do this.
